server {
    listen 80;
    server_name localhost;

    # A főoldal kezelése
    location / {
        root /usr/share/nginx/html/my-website;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # A Vite eszközök (/my-website/assets/...) kezelése
    location /my-website {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /my-website/index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
